version: '3'
services:
  back:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
    ports:
      - 3001:8080
    volumes:
      - .:/app:z

  front:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app/ui:z
