FROM node:16.13.2-alpine3.15

WORKDIR /app

COPY package*.json /workspace/

RUN apk add --no-cache bash
RUN yarn install --ignore-scripts && yarn build:ui

COPY . /app

EXPOSE 3000
ENV PORT 3000

CMD ["yarn", "start:ui"]
