FROM node:14.8.0-alpine3.10

WORKDIR /app

COPY package*.json /workspace/

RUN apk add --no-cache bash
RUN apk add --no-cache git
RUN yarn install --ignore-scripts && yarn build

COPY . /app

EXPOSE 8080

CMD ["yarn", "start"]
